stages:
  - e2e-test

cypress-e2e:
  stage: e2e-test
  image:
    name: cypress/browsers:24.16.0
    entrypoint: [""] # Clears any default entrypoint interference

  # Spin up the database container alongside the Cypress container
  services:
    - name: postgres:18.3-alpine
      alias: postgres-db # Alias to reach the DB via hostname

  # Set database credentials and connection variables
  variables:
    npm_config_cache: "/tmp/npm-cache"
    NODE_ENV: "production"
    NPM_CONFIG_PRODUCTION: false
    NODE_OPTIONS: "--max-old-space-size=4096"
    CYPRESS_CACHE_FOLDER: "/root/.cache/Cypress"
    # Set default values if UI variables are empty/missing
    POSTGRES_DB: "mydatabase"
    POSTGRES_USER: "myusername"
    POSTGRES_PASSWORD: "mypassword"

    # Constructed connection string
    DATABASE_URL: "postgresql://myusername:mypassword@postgres-db:5432/mydatabase?schema=public&connection_limit=20"
    # NestJS Backend Environment Variables
    JWT_SECRET: "default_secret_key"
    JWT_EXPIRES_IN: "1d"
    USERNAME: "bossmann"
    PASSWORD: "admin12345"
    UPLOAD_LOCATION: "./uploads"

  before_script:
    - rm -rf /tmp/npm-cache
    - rm -rf node_modules
    - rm -rf ~/.npm
    - rm -rf /root/.npm
    - npm cache clean --force
    - npm install --no-audit --no-fund

  script:
    - npx prisma generate
    - npx prisma db push
    - npm run seed

    # - npx prisma migrate deploy  # Creates all tables instantly

    - npx nx run libs:build
    - npx nx build backend --skip-nx-cache
    - npx nx build frontend --configuration=production
    - npx wait-on tcp:postgres-db:5432 --timeout 30000

    # 2. Start NestJS Backend in background
    - node dist/apps/backend/main.js &
    - npx wait-on http-get://127.0.0.1:3000/api --timeout 60000

    # 3. Serve production build in background (NO esbuild dev server deadlock!)
    # - npx serve -s dist/apps/frontend/browser -l 4200 &
    # - npx wait-on http-get://127.0.0.1:4200 --timeout 30000

    # 4. Run Cypress against static production bundle
    #node -e 'fetch("http://127.0.0.1:3000/api/products?type=BOOK&page=1&limit=12&isDiscounted=false").then(r => r.json()).then(d => console.log(JSON.stringify(d, null, 2)))'
    - npx nx run frontend:e2e

  artifacts:
    when: on_failure
    paths:
      - apps/frontend/cypress/videos
      - apps/frontend/cypress/screenshots
    expire_in: 1 week