stages:
#  - vitest
  - e2e-backend
#  - e2e-frontend

.node_env_template: &node_env_template
  image:
    name: cypress/browsers:24.16.0
    entrypoint: [""]

  # Set database credentials and connection variables
  variables:
    npm_config_cache: "/tmp/npm-cache"
    NODE_ENV: "production"
    NPM_CONFIG_PRODUCTION: false
    NODE_OPTIONS: "--max-old-space-size=8192"
    CYPRESS_CACHE_FOLDER: "/root/.cache/Cypress"
    # Set default values if UI variables are empty/missing
    POSTGRES_DB: "mydatabase"
    POSTGRES_USER: "myusername"
    POSTGRES_PASSWORD: "mypassword"

    # Constructed connection string
    DATABASE_URL: "postgresql://myusername:mypassword@postgres-db:5432/mydatabase?schema=public&connection_limit=20"
    # NestJS Backend Environment Variables
    JWT_SECRET: "default_secret_key"
    JWT_EXPIRES_IN: "1d"
    USERNAME: "bossmann"
    PASSWORD: "admin12345"
    TEST_NAME: "testinguser"
    TEST_PASSWORD: "tester12345"
    UPLOAD_LOCATION: "./uploads"

  # Spin up the database container alongside the Cypress container
  services:
    - name: postgres:18.3-alpine
      alias: postgres-db # Alias to reach the DB via hostname

  before_script:
    - npm install --no-audit --no-fund

#unit-tests:
#  stage: vitest
#  <<: *node_env_template
#  script:
#    - npx nx test frontend --skip-nx-cache
#  rules:
#    - when: always
#
cypress-e2e-backend:
  stage: e2e-backend
  <<: *node_env_template
  script:
    - echo "Starting NestJS Backend API (E2E) Tests"
    - npx prisma generate
    - npx prisma db push
    - npm run seed

    - npx nx run libs:build
    - npx nx build backend --skip-nx-cache
    - npx nx run backend:e2e

#cypress-e2e-frontend:
#  stage: e2e-frontend
#  <<: *node_env_template
#  script:
#    - npx prisma generate
#    - npx prisma db push
#    - npm run seed
#
#    - npx nx run libs:build
#    - npx nx build backend --skip-nx-cache
#    - npx nx build frontend --configuration=production --skip-nx-cache
#    - npx wait-on tcp:postgres-db:5432 --timeout 30000
#
#   # 2. Start NestJS Backend in background
#    - npx nx serve backend --configuration=production &
#    - npx wait-on http-get://127.0.0.1:3000/api --timeout 60000
#    - npx nx run frontend:e2e

  artifacts:
    when: on_failure
    paths:
      - apps/frontend/cypress/videos
      - apps/frontend/cypress/screenshots
    expire_in: 1 week